"""Control diagnostics tool.

Displays PD controller outputs for both the Open and Obstacle challenges,
helping to tune gains and visualise correction signals.
"""

from utils import cv2
from utils.tools.base_tool import BaseTool
from src.modules.lib.controller import PD
from src.modules.lib.config import Config


class ControlTool(BaseTool):
    """Tool for viewing PD controller outputs in real time.

    Computes wall-following, corner-turn, and obstacle-avoidance
    corrections for both challenge types and overlays them on the frame.
    """
    def __init__(self):
        super().__init__(name="control", description="View control status and diagnostics")
        self.open_challenge_pd_straight = PD(
            *Config.OpenChallengeConfig.WALL_FOLLOW_KPKD)
        self.open_challenge_pd_turn = PD(
            *Config.OpenChallengeConfig.CORNER_TURN_KPKD)
        self.obstacle_challenge_straight_pd = PD(
            *Config.ObstacleChallengeConfig.WALL_FOLLOW_KPKD)
        self.obstacle_challenge_turn_pd = PD(
            *Config.ObstacleChallengeConfig.CORNER_TURN_KPKD)
        self.obstacle_challenge_obstacle_pd = PD(
            *Config.ObstacleChallengeConfig.OBSTACLE_AVOID_KPKD)

    def _compute(self, data, *args, **kwargs):
        """Compute PD controller outputs from vision data.

        Runs wall-following, corner-turn, and obstacle-avoidance PD
        controllers for both the Open and Obstacle challenges.

        :param data: Vision pipeline output tuple.
        :returns: Dict mapping correction names to float values.
        """
        zone, walls, obstacles, corner_lines, wall_dists, obstacle_dists = data
        open_challenge_straight_correction = self.open_challenge_pd_straight.tick(
            wall_dists["left"] - wall_dists["right"]
        )
        open_challenge_turn_correction = self.open_challenge_pd_turn.tick(
            # Biggest corner line x - frame center
            corner_lines[0].x_centroid -
            Config.CameraConfig.FORMAT["size"][0] // 2
            if corner_lines else 0
        )
        obstacle_challenge_straight_correction = self.obstacle_challenge_straight_pd.tick(
            wall_dists["left"] - wall_dists["right"]
        )
        obstacle_challenge_turn_correction = self.obstacle_challenge_turn_pd.tick(
            # Biggest corner line x - frame center
            corner_lines[0].x_centroid -
            Config.CameraConfig.FORMAT["size"][0] // 2
            if corner_lines else 0
        )
        # obstacle_challenge_obstacle_correction  = self.obstacle_challenge_obstacle_pd.tick(
        #    obstacle_path_x, Config.CameraConfig.FORMAT["size"][0] // 2
        # Target -> cubic spline generated by vision, current value -> frame center, want to steer towards the target path
        # Although is is probally wrong because the target is absolute relative to point where it is computed, and not
        # to the current position, so kenmatic PID is probally better but uh I can't really do that because we don't have
        # an encoder
        # In other words... just pray :3
        # hey i mean at least it's recomputed every 5 frames
        # )

        return {
            "Open Challenge Straight Correction": open_challenge_straight_correction,
            "Open Challenge Turn Correction": open_challenge_turn_correction,
            "Obstacle Challenge Straight Correction": obstacle_challenge_straight_correction,
            "Obstacle Challenge Turn Correction": obstacle_challenge_turn_correction,
            # obstacle_challenge_obstacle_correction,
            "Obstacle Challenge Obstacle Correction": 0,
        }

    def _draw(self, data, *args, **kwargs):
        """Draw PD controller outputs as text overlays on the frame.

        :param data: Vision pipeline output tuple.
        """
        data = self._compute(data, *args, **kwargs)
        for key, value in data.items():
            cv2.putText(self.frame, f"{key}: {value:.2f}", (10, 30 + 30 * list(
                data.keys()).index(key)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.imshow("Control Status", self.frame)

    def _draw_no_perspective(self, data, *args, **kwargs):
        """Draw PD outputs on the unwarped frame.

        Perspective transforms are non-linear, so outputs differ between
        the warped and unwarped views. Both are displayed for debugging.

        :param data: Vision pipeline output tuple.
        """
        self._draw(data, *args, **kwargs)
        cv2.imshow("Control Status No Transform", self.frame)
        # Because perspective transform is nonlinear the outputs will be different,
        # because it doesn't preserve proportionality, so we need to draw them separately for debugging purposes
        # A perspective transform warps the image such that parrallel lines can converge, which is a projective transformation
        # And is neither affine or linear.


async def run_control_tool():
    """Entry point for the control diagnostics tool."""
    tool = ControlTool()
    await tool.run()
