"""Obstacle Challenge runner.

Sets up shared memory, camera and vision subprocesses, then runs the
main control loop for the WRO obstacle challenge course.
"""

import asyncio
from typing import Literal
from piclient.core import logger  # pyright: ignore[reportMissingTypeStubs]
# pyright: ignore[reportMissingTypeStubs]
from piclient.core.interface import Client, AsyncCamera
# pyright: ignore[reportMissingTypeStubs]
from piclient.core.vision import AsyncMultiprocessingVisionProcessor
# pyright: ignore[reportMissingTypeStubs]
from piclient.core.lib import PD, GLOBAL_CONFIG, export, load_configuration
import multiprocessing as mp
from multiprocessing import shared_memory


@export
async def run_obstacle_challenge() -> None:
    """Asynchronus runner for the *obstacle challenge*"""

    load_configuration()

    async with Client() as client:
        config = GLOBAL_CONFIG().ObstacleChallengeConfig
        wall_follow = PD(*config.WALL_FOLLOW_KPKD)
        obstacle_avoid = PD(*config.OBSTACLE_AVOID_KPKD)
        corner_turn_controller = PD(*config.CORNER_TURN_KPKD)

        # Starting code here
        state: Literal["Straight", "Turn"] = "Straight"
        camera_process, vision_process, shm = None, None, None

        try:

            try:
                shm = shared_memory.SharedMemory(
                    create=True, size=512*384*3, name="camera_frame")
            except FileExistsError:
                try:
                    shm = shared_memory.SharedMemory(name="camera_frame")
                    shm.close()
                    shm.unlink()
                    # Make sure it has exactly the size we need, and is empty
                    shm = shared_memory.SharedMemory(
                        create=True, size=512*384*3, name="camera_frame")
                except FileNotFoundError:
                    # The shared memory segment disappeared between create and cleanup attempts, try again
                    shm = shared_memory.SharedMemory(
                        create=True, size=512*384*3, name="camera_frame")

            cam_receiver, cam_sender = mp.Pipe(duplex=False)
            camera_process = mp.Process(
                target=AsyncCamera.camera_process_context_manager, args=(shm.name, cam_sender,))
            camera_process.start()

            data_receiver, data_sender = mp.Pipe(duplex=False)
            vision_process = mp.Process(target=AsyncMultiprocessingVisionProcessor.vision_process_context_manager, args=(
                shm.name, cam_receiver, data_sender,))
            vision_process.start()

            # Camera process dumps frames into shared memory, and sends a signal through cam_sender when a new frame is ready.
            # Vision process listens on cam_receiver for the signal, then reads the frame from shared memory, processes it, and sends the results back through data_sender.
            # Staticmethod data_yielder polls the data_receiver for data and yields it to the main loop.

            async for zone, walls, obstacles, corner_lines, wall_x_diffs, obstacle_x_diffs, obstacle_path_x in AsyncMultiprocessingVisionProcessor.async_pipe_reader(data_receiver):

                logger.debug(
                    f"Zone: {zone}, Walls: {walls}, Obstacles: {obstacles}, Corner Lines: {corner_lines}, Wall Dists: {wall_x_diffs}, Obstacle Dists: {obstacle_x_diffs}, Obstacle Path X: {obstacle_path_x}")

                match state:
                    case "Straight":
                        if corner_lines:
                            state = "Turn"
                        else:
                            if obstacles:
                                turn_correction = obstacle_avoid.tick(
                                    obstacle_path_x, GLOBAL_CONFIG(
                                    ).CameraConfig.FORMAT["size"][0] // 2
                                    # Target -> cubic spline generated by vision, current value -> frame center, want to steer towards the target path
                                    # Although is is probably wrong because the target is absolute relative to point where it is computed, and not
                                    # to the current position, so kinematic PID is probably better but uh I can't really do that because we don't have
                                    # an encoder
                                    # In other words... just pray :3
                                    # hey i mean at least it's recomputed every 5 frames
                                )
                                asyncio.create_task(client.drive_motors(
                                    0.5, int(turn_correction), 0.1))
                            else:
                                turn_correction = wall_follow.tick(
                                    wall_x_diffs["left"] - wall_x_diffs["right"])
                                asyncio.create_task(client.drive_motors(
                                    0.5, int(turn_correction), 0.1))

                    case "Turn":
                        if not corner_lines:
                            state = "Straight"
                        else:
                            turn_correction = corner_turn_controller.tick(
                                # Biggest corner line, 192 is frame center
                                corner_lines[0].x_centroid - GLOBAL_CONFIG().CameraConfig.FORMAT["size"][0] // 2)
                            asyncio.create_task(client.drive_motors(
                                0.5, int(turn_correction), 0.1))

                    case _:
                        logger.error(f"Invalid state {state}")
                        state = "Straight"
        finally:
            logger.info(
                "Terminating processes and cleaning up shared memory...")
            try:
                if camera_process and camera_process.is_alive():
                    camera_process.terminate()
                    camera_process.join(timeout=1)

                if vision_process and vision_process.is_alive():
                    vision_process.terminate()
                    vision_process.join(timeout=1)

                if shm:
                    shm.close()
                    shm.unlink()

                logger.info("Exited cleanly")
            except Exception as e:
                logger.error(f"Error during cleanup: {e}")
                logger.warning(
                    f"Leaked memory segments and processes may need to be cleaned up manually. Good luck finding them michael -_-")
