[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/piclient/cli"]


[project]
name = "piclient-cli"
version = "0.1.0"
authors = [
    { name = "Michael Xie", email = "wenmike.xie@gmail.com" },
]
description = "Apostla team WRO FE 2026 CLI entry point"

requires-python = ">=3.10"
dependencies = [
    "piclient",
]

classifiers = [
    "Private :: Do Not Upload",
]


[project.scripts]
wro = "piclient.cli:main"
