name: Deploy documentation to firebase
permissions:
  contents: read

on: [push]

jobs:
  deploy-api-reference:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies and activate venv
      run: | # I really should add a requirements.txt for docs but this is fine for now
        cd PiClient
        python -m venv .venv
        source .venv/bin/activate
        pip install ./piclient-cli ./piclient-core ./piclient-obstacle_challenge ./piclient-open_challenge
        pip install sphinx furo

    - name: Build documentation
      run: |
        cd PiClient
        source .venv/bin/activate
        cd docs
        make html

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      env:
        JSON_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$JSON_CREDENTIALS" > firebase-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-credentials.json
        firebase deploy
        rm -f firebase-credentials.json
